### ISSUE TITLE
Something wrong when I converted pcd files to depth images, using the python script 

### ISSUE THREAD

**Issue by Zhangeaky** [dougsm/ggcnn#32]
@dougsm 
Thank you for your code and paper first! 
when I used the file **generate_cornell_depth.py** with the commandline 
"python -m utils.dataset_processing.generate_cornell_depth <Path To Dataset>", the result  depth picture is strange,all result depth    
images look the same,just like this 
![2020-08-07 15-56-02屏幕截图](https://user-images.githubusercontent.com/55437106/89623028-8bdf1a80-d8c6-11ea-8e60-c317da2dc7ef.png)

**Comment by dougsm** [comment]
Hey @Zhangeaky 
I've seen this before. I think the problem isn't that the files are incorrect, but rather the image viewer (e.g. the default viewer in ubuntu) doesn't know how to interpret the floating point data.

To test, you can try and visualise it using matplotlib instead:
```
import matplotlib.pyplot as plt
import imageio

img = imageio.imread("<path_to_img.tiff>")
plt.imshow(img)
plt.show()
```

Hopefully that will show that the correct data has been saved.  Otherwise, shoot me a reply and I'll take another look.

**Comment by Zhangeaky** [comment]
Thanks! I just solved it by your solution
